---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/ParquetSharp.DataFrame"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/ParquetSharp.DataFrame.Test"
    schedule:
      interval: "daily"
